import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from 'next-themes';
import Transitions from "~/components/layout/Transitions";

import "../styles/index.css";
import Header from "~/components/layout/header";
import { QueryClientProvider } from "@tanstack/react-query";
import { QueryProvider } from "~/providers/queryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        maxWidth: '1000px',
        margin: '0 auto',
        padding: '1rem',
      }}>
        <ThemeProvider attribute="class">
          <Header />
          <QueryProvider>
            <Transitions>
              <div className="mt-12 p-4">{children}</div>
            </Transitions>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
